DROP TABLE IF EXISTS RSS3WeaveVMArchiver;

CREATE TABLE IF NOT EXISTS RSS3WeaveVMArchiver (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NetworkBlockId INT UNIQUE,
    WeaveVMArchiveTxid VARCHAR(66) UNIQUE
);